// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AppClient struct {
	ID               pgtype.UUID
	UserPoolID       pgtype.UUID
	TenantID         pgtype.UUID
	ClientName       string
	ClientID         pgtype.Text
	ClientSecretHash pgtype.Text
	AppType          string
	TokenTtlOverride pgtype.Int4
	Metadata         []byte
	IsActive         bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type AuditLog struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	ActorID      pgtype.UUID
	ActorType    string
	Action       string
	ResourceType string
	ResourceID   pgtype.UUID
	OldValue     []byte
	NewValue     []byte
	IpAddress    *netip.Addr
	UserAgent    pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type Tenant struct {
	ID         pgtype.UUID
	AccountID  string
	Name       string
	Email      string
	Password   string
	Phone      pgtype.Text
	WebsiteUrl pgtype.Text
	Address    []byte
	Status     string
	Settings   []byte
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type User struct {
	ID            pgtype.UUID
	TenantID      pgtype.UUID
	UserPoolID    pgtype.UUID
	FirstName     pgtype.Text
	LastName      pgtype.Text
	DisplayName   string
	Email         string
	EmailVerified bool
	Phone         pgtype.Text
	PhoneVerified bool
	AvatarUrl     pgtype.Text
	Department    pgtype.Text
	PasswordHash  pgtype.Text
	MfaEnabled    bool
	MfaSecret     pgtype.Text
	LastLoginAt   pgtype.Timestamptz
	IsActive      bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type UserPool struct {
	ID                pgtype.UUID
	TenantID          pgtype.UUID
	PoolName          string
	Description       pgtype.Text
	SignInMethods     []byte
	AppType           string
	MfaRequired       bool
	PasswordPolicy    []byte
	TokenTtlSeconds   int32
	RefreshTtlSeconds int32
	MaxDevices        pgtype.Int4
	AllowedOrigins    []string
	IsActive          bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
}

type VerificationToken struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	TenantID        pgtype.UUID
	TokenHash       string
	AppClientID     pgtype.UUID
	Type            string
	RequestedFromIp pgtype.Text
	ExpiresAt       pgtype.Timestamptz
	UsedAt          pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}
