// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const testTenants = `-- name: TestTenants :exec
INSERT INTO "tenants"(
    name,
    email,
    password,
    phone,
    website_url,
    address,
    status,
    settings
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type TestTenantsParams struct {
	Name       string
	Email      string
	Password   string
	Phone      pgtype.Text
	WebsiteUrl pgtype.Text
	Address    []byte
	Status     string
	Settings   []byte
}

func (q *Queries) TestTenants(ctx context.Context, arg TestTenantsParams) error {
	_, err := q.db.Exec(ctx, testTenants,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.WebsiteUrl,
		arg.Address,
		arg.Status,
		arg.Settings,
	)
	return err
}
