// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM verification_tokens WHERE token_hash = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, tokenHash)
	return err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, COALESCE(user_id::TEXT, '') as user_id, COALESCE(app_client_id::TEXT, '') as app_client_id, COALESCE(tenant_id::TEXT, '') as tenant_id, token_hash, expires_at, created_at
FROM verification_tokens
WHERE token_hash = $1
`

type GetRefreshTokenByHashRow struct {
	ID          pgtype.UUID
	UserID      interface{}
	AppClientID interface{}
	TenantID    interface{}
	TokenHash   string
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (GetRefreshTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i GetRefreshTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppClientID,
		&i.TenantID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertTenantRefreshToken = `-- name: InsertTenantRefreshToken :exec
INSERT INTO verification_tokens (tenant_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type InsertTenantRefreshTokenParams struct {
	TenantID  pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertTenantRefreshToken(ctx context.Context, arg InsertTenantRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertTenantRefreshToken, arg.TenantID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const insertUserRefreshToken = `-- name: InsertUserRefreshToken :exec
INSERT INTO verification_tokens (user_id, app_client_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertUserRefreshTokenParams struct {
	UserID      pgtype.UUID
	AppClientID pgtype.UUID
	TokenHash   string
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) InsertUserRefreshToken(ctx context.Context, arg InsertUserRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertUserRefreshToken,
		arg.UserID,
		arg.AppClientID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}
